application:
  database:
    mongodb:
      uri: mongodb://localhost:27017

  session:
    timeout: 30
  refreshToken:
    timeout: 3

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: merscov99

    context:
      exchangeName: exchange.context
      user:
        requestQueueName: context.user.request
        requestQueueRoutingKey: routingKey.context.user.request
        responseQueueName: context.user.response
        responseQueueRoutingKey: routingKey.context.user.response
